name: deploy
on:
  push:
    branches: [master]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      - run: yarn install
      - run: yarn build
      - uses: aquiladev/ipfs-action@v0.1.5
        id: ipfs-upload
        with:
          path: ./dist
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
      - run: echo "Uploaded hash: ${{ steps.ipfs-upload.outputs.hash }}"
