name: deploy
on:
  push:
    branches: [master]
jobs:
  deploy-to-ipfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      - run: yarn install
      - run: yarn build
      - uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        id: ipfs-upload
        with:
          pin-name: 'smoldot-browser-demo'
          path: './dist'
          pinata-api-key: ${{ secrets.PINATA_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
          remove-old: true
      - run: |
          echo "Uploaded hash: ${{ steps.ipfs-upload.outputs.hash }}"
